# Generated by Django 5.2rc1 on 2025-03-27 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_group_group_permission_user_group'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group_Permission',
            new_name='Group_Permissions',
        ),
        migrations.RenameModel(
            old_name='User_Group',
            new_name='User_Groups',
        ),
    ]
