# Generated by Django 5.2rc1 on 2025-03-27 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_taskstatus_employee_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='up_date_at',
            new_name='updated_at',
        ),
    ]
